/**
 * CDS Plugin — cap-handler-framework
 *
 * CAP plugins run their registration code at require() time.
 * This file is required by CAP on startup (because package.json has
 * "cds": { "plugin": true }). All cds.on() registrations happen here,
 * at module load time — NOT inside an exported function.
 *
 * ─── What this plugin does ──────────────────────────────────────────────────
 *
 *  1. On `cds.on('served', ...)`: scans every srv/<service>/handlers/ directory
 *     and generates (or updates) an `index.ts` file listing all handler classes.
 *
 *  2. Safe write: compares new content to the existing file before writing.
 *     If content is identical, no file is written → no reload loop.
 *
 *  3. File watcher: sets up a directory watcher on the srv/ tree.
 *     When a *Handler.ts or *Handler.js file is added or deleted the index
 *     is regenerated automatically without a manual server restart.
 *     The watcher is set up ONCE (module-level guard) to survive hot-reloads.
 *
 * ─── @sap/cds singleton ──────────────────────────────────────────────────────
 *
 *  The plugin must share the SAME @sap/cds instance as the host CAP server.
 *  Because this file is symlinked (file: dependency), Node.js would normally
 *  resolve @sap/cds from cap-handler-framework/node_modules — a DIFFERENT
 *  instance. We prevent that by resolving from process.cwd() instead.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Resolve @sap/cds from the consuming project's CWD ────────────────────────
// This ensures the plugin shares the SAME singleton as the host CAP server.
const cds = require(require.resolve('@sap/cds', { paths: [process.cwd()] }));
const LOG = cds.log('cap-handler-framework');

LOG.debug('cap-handler-framework cds-plugin loaded');

// ── Module-level state (survives hot-reloads within the same process) ────────
let watcherInitialized = false;

// ── Register on 'served' (fires after all services are mounted) ───────────────
cds.on('served', async () => {
  try {
    await autoGenerateHandlerIndices();
  } catch (err) {
    LOG.warn('Failed to auto-generate handler indices:', err.message);
  }

  // Set up the filesystem watcher once per process lifetime
  if (!watcherInitialized) {
    watcherInitialized = true;
    setupHandlerWatcher();
  }
});

// ── Index generation ─────────────────────────────────────────────────────────

/**
 * Scan all srv/<service>/handlers/ directories and generate index files.
 */
async function autoGenerateHandlerIndices() {
  const srvDir = path.join(cds.root, 'srv');

  if (!fs.existsSync(srvDir)) {
    LOG.debug('No srv/ directory found — skipping handler index generation');
    return;
  }

  const entries = fs.readdirSync(srvDir);
  let writtenCount = 0;

  for (const entry of entries) {
    const serviceDir = path.join(srvDir, entry);
    if (!fs.statSync(serviceDir).isDirectory()) continue;

    const handlersDir = path.join(serviceDir, 'handlers');
    if (!fs.existsSync(handlersDir)) continue;

    const written = generateHandlerIndex(handlersDir, entry);
    if (written) {
      LOG.info(`✅  Generated handlers/index.ts for service: ${entry}`);
      writtenCount++;
    }
  }

  if (writtenCount > 0) {
    LOG.info(`Generated ${writtenCount} handler index file(s)`);
  } else {
    LOG.debug('All handler index files are up to date');
  }
}

/**
 * Generate (or update) the index.ts for one service's handlers/ directory.
 */
function generateHandlerIndex(handlersDir, serviceName) {
  const entitiesDir = path.join(handlersDir, 'entities');
  const proxiesDir  = path.join(handlersDir, 'proxies');

  const entities = scanHandlerFiles(entitiesDir);
  const proxies  = scanHandlerFiles(proxiesDir);

  if (entities.length === 0 && proxies.length === 0) {
    LOG.debug(`No handlers found in ${serviceName}/handlers — skipping`);
    return false;
  }

  const content  = buildIndexContent(serviceName, entities, proxies);
  const filePath = path.join(handlersDir, 'index.ts');

  return safeWriteFile(filePath, content);
}

/**
 * Return sorted handler base-names (without extension) from a directory.
 */
function scanHandlerFiles(dir) {
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir)
    .filter(f => f.endsWith('Handler.ts') || f.endsWith('Handler.js'))
    .map(f => f.replace(/\.(ts|js)$/, ''))
    .sort();
}

/**
 * Build the string content for an index.ts file.
 */
function buildIndexContent(serviceName, entities, proxies) {
  const total = entities.length + proxies.length;
  const lines = [
    '/**',
    ' * AUTO-GENERATED by cap-handler-framework',
    ' *',
    ' * This file is automatically generated.',
    ' * DO NOT EDIT MANUALLY — your changes will be overwritten.',
    ' *',
    ' * To add a new handler:',
    ' *   1. Create YourEntityHandler.ts in entities/ or proxies/',
    ' *   2. The server will regenerate this file automatically.',
    ' *',
    ` * Service  : ${serviceName}`,
    ` * Handlers : ${total} total (${entities.length} entities, ${proxies.length} proxies)`,
    ' */',
    '',
  ];

  if (entities.length > 0) {
    lines.push('// Entity Handlers');
    entities.forEach(name => lines.push(`import ${name} from './entities/${name}';`));
    lines.push('');
  }

  if (proxies.length > 0) {
    lines.push('// Proxy Handlers');
    proxies.forEach(name => lines.push(`import ${name} from './proxies/${name}';`));
    lines.push('');
  }

  lines.push('/**');
  lines.push(' * All handler classes for this service.');
  lines.push(' * The HandlerRegistry instantiates and registers each one.');
  lines.push(' */');
  lines.push('export const HANDLER_CLASSES = [');

  if (entities.length > 0) {
    lines.push(`  // Entity handlers (${entities.length})`);
    entities.forEach(name => lines.push(`  ${name},`));
    if (proxies.length > 0) lines.push('');
  }

  if (proxies.length > 0) {
    lines.push(`  // Proxy handlers (${proxies.length})`);
    proxies.forEach(name => lines.push(`  ${name},`));
  }

  lines.push('];', '');

  return lines.join('\n');
}

// ── Safe write ───────────────────────────────────────────────────────────────

/**
 * Write content to a file ONLY if the normalised content has changed.
 * Prevents unnecessary cds watch reload loops.
 */
function safeWriteFile(filePath, newContent) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf8');
    if (normalise(existing) === normalise(newContent)) {
      LOG.debug(`No change — skipping write: ${path.relative(cds.root, filePath)}`);
      return false;
    }
  }

  fs.writeFileSync(filePath, newContent, 'utf8');
  LOG.debug(`Written: ${path.relative(cds.root, filePath)}`);
  return true;
}

/**
 * Strip volatile lines (timestamps, old headers) before comparing content.
 */
function normalise(content) {
  return content
    .replace(/^ \* Generated\s*:.+$/gm, '')   // old "Generated: <date>" lines
    .replace(/^ \* AUTO-GENERATED by .+$/gm, ' * AUTO-GENERATED') // normalize brand
    .trim();
}

// ── File watcher ─────────────────────────────────────────────────────────────

/**
 * Watch srv/ for *Handler.ts/js add/remove events and regenerate indices.
 * Uses chokidar (bundled with cds-dk) or falls back to native fs.watch.
 */
function setupHandlerWatcher() {
  const srvDir = path.join(cds.root, 'srv');
  if (!fs.existsSync(srvDir)) return;

  const onChange = debounce(async () => {
    try {
      await autoGenerateHandlerIndices();
    } catch (err) {
      LOG.warn('Handler watcher regeneration failed:', err.message);
    }
  }, 200);

  // ── Try chokidar first ──────────────────────────────────────────────────
  try {
    const chokidar = require('chokidar');
    const pattern  = path.join(srvDir, '*', 'handlers', '**', '*Handler.{ts,js}');

    const watcher = chokidar.watch(pattern, {
      ignoreInitial    : true,
      persistent       : false,
      awaitWriteFinish : { stabilityThreshold: 100, pollInterval: 50 },
    });

    watcher
      .on('add',    f => { LOG.debug(`Handler added: ${f}`);   onChange(); })
      .on('unlink', f => { LOG.debug(`Handler removed: ${f}`); onChange(); });

    LOG.info('Handler file watcher started (chokidar)');
    return;
  } catch (_) {
    // chokidar not available — fall through to fs.watch
  }

  // ── Fallback: native fs.watch ───────────────────────────────────────────
  try {
    fs.watch(srvDir, { recursive: true, persistent: false }, (eventType, filename) => {
      if (!filename) return;
      if (
        (filename.endsWith('Handler.ts') || filename.endsWith('Handler.js')) &&
        !filename.includes('index')
      ) {
        LOG.debug(`fs.watch detected change: ${filename}`);
        onChange();
      }
    });
    LOG.info('Handler file watcher started (fs.watch fallback)');
  } catch (err) {
    LOG.warn('Could not start handler file watcher:', err.message);
  }
}

// ── Utilities ────────────────────────────────────────────────────────────────

function debounce(fn, ms) {
  let timer;
  return function (...args) {
    clearTimeout(timer);
    timer = setTimeout(() => fn.apply(this, args), ms);
  };
}
