/**
 * CDS Plugin Integration (CDS 9 compatible)
 * 
 * This plugin provides:
 * 1. Auto-generation of handler index files
 * 2. Passive handler registration (via explicit registerHandlers() calls)
 */

const fs = require('fs');
const path = require('path');

module.exports = function() {
  const cds = require('@sap/cds');
  const LOG = cds.log('cap-handler-framework');
  
  LOG.debug('CAP Handler framework plugin loaded');

  // Hook into CDS bootstrap to auto-generate handler indices
  cds.on('bootstrap', async () => {
    try {
      await autoGenerateHandlerIndices();
    } catch (error) {
      LOG.warn('Failed to auto-generate handler indices:', error.message);
    }
  });
};

/**
 * Auto-generate index.ts files for all services with handlers
 */
async function autoGenerateHandlerIndices() {
  const cds = require('@sap/cds');
  const LOG = cds.log('cap-handler-framework');
  
  // Find srv directory
  const srvDir = path.join(cds.root, 'srv');
  
  if (!fs.existsSync(srvDir)) {
    LOG.debug('No srv directory found, skipping handler index generation');
    return;
  }

  LOG.info('Auto-generating handler index files...');

  // Find all service directories
  const entries = fs.readdirSync(srvDir);
  let generatedCount = 0;

  for (const entry of entries) {
    const fullPath = path.join(srvDir, entry);
    
    // Skip files, only process directories
    if (!fs.statSync(fullPath).isDirectory()) continue;
    
    const handlersDir = path.join(fullPath, 'handlers');
    
    // Check if handlers directory exists
    if (fs.existsSync(handlersDir)) {
      const generated = generateHandlerIndex(handlersDir, entry);
      if (generated) {
        LOG.info(`✅ Generated handlers/index.ts for ${entry}`);
        generatedCount++;
      }
    }
  }

  if (generatedCount > 0) {
    LOG.info(`Generated ${generatedCount} handler index file(s)`);
  } else {
    LOG.debug('No handler directories found');
  }
}

/**
 * Generate index.ts file for a specific handlers directory
 * 
 * @param {string} handlersDir - Path to handlers directory
 * @param {string} serviceName - Name of the service
 * @returns {boolean} - True if file was generated
 */
function generateHandlerIndex(handlersDir, serviceName) {
  const cds = require('@sap/cds');
  const LOG = cds.log('cap-handler-framework');

  // Scan for handler files in entities/ and proxies/ subdirectories
  const entitiesDir = path.join(handlersDir, 'entities');
  const proxiesDir = path.join(handlersDir, 'proxies');
  
  const entities = [];
  const proxies = [];

  // Scan entities directory
  if (fs.existsSync(entitiesDir)) {
    const files = fs.readdirSync(entitiesDir);
    for (const file of files) {
      if (file.endsWith('Handler.ts') || file.endsWith('Handler.js')) {
        const name = file.replace(/\.(ts|js)$/, '');
        entities.push(name);
      }
    }
  }

  // Scan proxies directory
  if (fs.existsSync(proxiesDir)) {
    const files = fs.readdirSync(proxiesDir);
    for (const file of files) {
      if (file.endsWith('Handler.ts') || file.endsWith('Handler.js')) {
        const name = file.replace(/\.(ts|js)$/, '');
        proxies.push(name);
      }
    }
  }

  // Only generate if there are handlers
  if (entities.length === 0 && proxies.length === 0) {
    LOG.debug(`No handlers found in ${serviceName}/handlers`);
    return false;
  }

  // Generate file content
  const lines = [
    '/**',
    ' * AUTO-GENERATED by @ctac/cap-handler-framework',
    ' * ',
    ' * This file is automatically generated during CDS bootstrap.',
    ' * DO NOT EDIT MANUALLY - Your changes will be overwritten!',
    ' * ',
    ' * To add a new handler:',
    ' * 1. Create YourEntityHandler.ts in entities/ or proxies/',
    ' * 2. Restart the server (cds watch will auto-regenerate this file)',
    ' * ',
    ` * Generated: ${new Date().toISOString()}`,
    ` * Service: ${serviceName}`,
    ` * Handlers: ${entities.length + proxies.length} total (${entities.length} entities, ${proxies.length} proxies)`,
    ' */',
    '',
  ];

  // Add entity handler imports
  if (entities.length > 0) {
    lines.push('// Entity Handlers');
    for (const name of entities.sort()) {
      lines.push(`import ${name} from './entities/${name}';`);
    }
    lines.push('');
  }

  // Add proxy handler imports
  if (proxies.length > 0) {
    lines.push('// Proxy Handlers');
    for (const name of proxies.sort()) {
      lines.push(`import ${name} from './proxies/${name}';`);
    }
    lines.push('');
  }

  // Add export
  lines.push('/**');
  lines.push(' * Export all handler classes');
  lines.push(' * The HandlerRegistry will use this to instantiate handlers');
  lines.push(' */');
  lines.push('export const HANDLER_CLASSES = [');
  
  if (entities.length > 0) {
    lines.push(`  // Entity handlers (${entities.length})`);
    for (const name of entities.sort()) {
      lines.push(`  ${name},`);
    }
    if (proxies.length > 0) {
      lines.push('  ');
    }
  }
  
  if (proxies.length > 0) {
    lines.push(`  // Proxy handlers (${proxies.length})`);
    for (const name of proxies.sort()) {
      lines.push(`  ${name},`);
    }
  }
  
  lines.push('];');
  lines.push('');

  const content = lines.join('\n');
  const indexPath = path.join(handlersDir, 'index.ts');

  // Write the file
  fs.writeFileSync(indexPath, content, 'utf8');
  
  return true;
}
